### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by sataaa** [ChaosinaCan/ClassicTabs#18]
I'm sorry, I didn't find the correct place for this. Please delete this and forgive me if this isn't the right place for it.

I'd like to request two new features, being able to remove the title from the tab (mousing over should still display the title; The tab should be resized to fit just the size of the favicon), and removing the X to close button from tabs (being still able to close them by middle click or right click -> close tab).

You've done a great job. Thanks.

**Comment by ChaosinaCan** [comment]
Neither of those things are possible with Opera's/Chrome's extensions system. I can modify tabs (move them around, create and destroy them, pin and unpin, focus them, etc.) but I cannot change what they look like.

**Comment by filbo** [comment]
Don't you run in every tab?  Title is just document.title, and I've seen things manipulate favicons by poking at link rel=icon (not sure there would be a _reliable_ method...)

Now if someone wanted you to change the _shape_ of the tabs, that might not be possible...

**Comment by ChaosinaCan** [comment]
The requested feature was to shrink the tab to just the favicon, but show the title on hover. Changing document.title would hide the title, but it would not cause Opera to shrink the size of the tab. There is also no way to be notified when the mouse is hovering over a tab.
