### ISSUE TITLE
Doesn't work after browser restart

### ISSUE THREAD

**Issue by bvm42** [ChaosinaCan/ClassicTabs#19]
If I close Opera (v 25.0) and start it up again, ClassicTabs doesn't "Activate the last active tab" when closing a Tab.  If I go into the extension manager and disable then enable the extension, then it again works properly.  Until I restart the browser...

**Comment by ChaosinaCan** [comment]
Have you tried updating Opera? The latest stable version is 26.

**Comment by bvm42** [comment]
Curiously, when Opera offered to update me from version 12 today, they gave me 25, not 26.  Seems like a goof on their part, assuming it's been out for a whole month as the change logs suggest.  Anyway, a few minutes ago, Opera auto-updated me to 26.  When it started up, ClassicTabs worked fine.  So I guess I withdraw my report.  Thanks.
