### ISSUE TITLE
intermittence

### ISSUE THREAD

**Issue by T015** [ChaosinaCan/ClassicTabs#24]
I've been using this app for years and in the last 2 months it's been giving me problems when trying to open a tab to the front. the app stops working everytime, I already checked the settings and there has been no change. Then I removed it and instllaed it again hoping a new version would have fixed the bug, but the same thing happens again and again. Everytime I have to enable and disable it again, but I'm getting tired. I better uninstall my browser because I'm losing a lot of interest.

**Comment by ChaosinaCan** [comment]
By "the app" do you mean Opera, or this extension?

This report doesn't give me enough info to be able to reproduce the problem. Can you list your settings or give me a screenshot? Is there a particular sequence of actions which causes it to stop working?

Also, if you open the extensions page (Ctrl+shift+E), click the "Developer mode" button, check "Collect errors" for Classic Tabs, and then do whatever causes the extension to fail, do any errors appear next to the "Collect errors" box?
