### ISSUE TITLE
Last tab bug

### ISSUE THREAD

**Issue by xDrVooDoox** [ChaosinaCan/ClassicTabs#25]
When i close any tab and activate last tab, the last and penultimate tabs switch places.

And wish. When i press ctrl+shift+T (open last close tab) it place to the end of list, but i wish that it placed to last postiton.

**Comment by ChaosinaCan** [comment]
I am aware of this, but I have no idea why it happens. My best guess is that this is a bug with Opera, since I'm not telling Opera to move tabs, and it corrects itself if you switch to the transposed tab. I reported it through Opera's bug report tool some number of months ago.

**Comment by ChaosinaCan** [comment]
Closing this in favor of #32, which has more details.
