### ISSUE TITLE
Switching back to previous tab when clicking on active tab not present.

### ISSUE THREAD

**Issue by DanLot** [ChaosinaCan/ClassicTabs#26]
The above function was available in Opera 12. Simply switching back and forth when clicking on active tab. Make it available, please!

**Comment by ChaosinaCan** [comment]
Unless it's been added recently, there is no way for an extensions to know when you have clicked on the active tab, so this isn't possible.

**Comment by ChaosinaCan** [comment]
No API for this exists.
