### ISSUE TITLE
disable 'tab motion' animation

### ISSUE THREAD

**Issue by filbo** [ChaosinaCan/ClassicTabs#30]
I use ClassicTabs to get tabs opened next to the current tab, and it works;
so suppose I hit ctrl-T to create a new tab, while the current tab is somewhere near the beginning of the tab bar.  Visually, what happens is: a new tab is created all the way on the right end of the tab bar; then quickly shuttles leftward until it reaches the intended place.

I can see in the code that you just call chrome.tabs.move(...).  You aren't doing that animation, it's a property of Chromium or Opera's tabs.move code.  But: maybe there's an option you can pass, or some trick, or some way of telling the browser that I just don't want that animation.

I'm not sure I can even explain why it bothers me.  But the bottom line is, I want the illusion that when I create a new tab, it appears, 'poof!', in the desired place.

So if there's any way to finagle that, please do.

**Comment by filbo** [comment]
(should be tagged 'enhancement')

**Comment by ChaosinaCan** [comment]
Unfortunately, no. Opera does not provide any way to change where tabs are created, so I force them to the right spot after they are created, and Opera also does not provide a way to disable the animation when a tab is moved.
