### ISSUE TITLE
Closing Last Tab closes Opera

### ISSUE THREAD

**Issue by mryanmarkryan** [ChaosinaCan/ClassicTabs#34]
Is this extension suppose to go to speed dial when the last browsing tab is closed? Is there a way? I use control-w a lot and always end up closing speed dial and closing opera. Then I have to start it again. Advice? Thank you!

**Comment by ChaosinaCan** [comment]
I don't believe there's any way for an extension to prevent Opera from closing itself. I only get notified after a tab has already been closed. While I could try to open a new tab really quickly before Opera closes, I doubt it would work consistently, if at all.
