### ISSUE TITLE
Suggesting a (hopefully) slight addition...

### ISSUE THREAD

**Issue by LittleMonkeyMojo** [ChaosinaCan/ClassicTabs#37]
I generally find that when I open a new tab from a link I prefer the new tab to be next to the current tab, but when I open a completely new (blank) tab (or the Speed Dial), I would prefer it at the end of my list of tabs.

You currently have config options which reads:
  Open Speed Dial next to the active tab, open other tabs at the end
and:
  Open all tabs next to the active tab

I'd like this option:
  Open Speed Dial at the end, Open all other tabs next to the active tab.

I also usually use the "and place consecutive new tabs in order".

Is this a possible addition?

**Comment by ChaosinaCan** [comment]
Isn't that Opera's default behavior?

**Comment by LittleMonkeyMojo** [comment]
Well, crap!

I have a memory of a time, when Opera would open everything at the end of the tabs list.
I also have a memory of Opera having an option for "open links next to current tab", but the ordering being munged.
Rather than
[A][B][C] becoming [A][1][2][3][B][C]

That it would become:
[A][B][C] becoming [A][3][2][1][B][C]

Now, I've just turned off tab related extensions, and it works like I would want it to work.


So...   sorry.  Nevermind. :-(

**Comment by ChaosinaCan** [comment]
No problem. I'll see if I can make the descriptions in the options page any clearer.
