### ISSUE TITLE
[Opera]  WebSocket connection to 'ws://127.0.0.1:35729/' net::ERR_CONNECTION_REFUSED

### ISSUE THREAD

**Issue by jpstotz** [ChaosinaCan/ClassicTabs#41]
When I build and install the Opera version as described in the project readme Opera is displaying an error that seem to occur every second:

> webextension-toolbox/client.js:14 (connect)
> WebSocket connection to 'ws://127.0.0.1:35729/' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

Context: `_generated_background_page.html`

Opera Version 64.0.3417.47

**Comment by joelspadin** [comment]
Are you building in development mode? That mode expects webpack to run a server so it can automatically reload the extension every time you edit it and it gets rebuilt. Try building the production version if you don't need that behavior.

**Comment by jpstotz** [comment]
Thanks I just used the first build instruction from the readme and therefore ended up with the development version. 

Using the production version solves the problem, however it would be good to have the installation instructions also for the production builds. As the output is a zip file at least in Opera the installation wasn't that straightforward as for the development build as there is no "install button". You really have to know that you have to activate the development mode and then drag&drop the zip file to the extensions window.
